# Generated from packages/sdk-spec/openapi.json by scripts/generate-routes.mjs — do not edit.
from __future__ import annotations

from typing import Optional

ROUTES: dict[str, tuple[str, str]] = {
    "Balance_getBalance": ("GET", "/v1/balance"),
    "CheckoutSessions_create": ("POST", "/v1/checkout/sessions"),
    "CheckoutSessions_retrieve": ("GET", "/v1/checkout/sessions/{id}"),
    "Merchants_addPayoutMethod": ("POST", "/v1/merchants/{id}/payout-methods"),
    "Merchants_confirmVerify": ("POST", "/v1/merchants/{id}/verify"),
    "Merchants_confirmVerifyMethod": ("POST", "/v1/merchants/{id}/payout-methods/{methodId}/verify"),
    "Merchants_create": ("POST", "/v1/merchants"),
    "Merchants_deletePayoutMethod": ("DELETE", "/v1/merchants/{id}/payout-methods/{methodId}"),
    "Merchants_getBalance": ("GET", "/v1/merchants/{id}/balance"),
    "Merchants_getById": ("GET", "/v1/merchants/{id}"),
    "Merchants_listAuditEvents": ("GET", "/v1/merchants/{id}/audit-events"),
    "Merchants_listOrGetByRef": ("GET", "/v1/merchants"),
    "Merchants_listPayoutMethods": ("GET", "/v1/merchants/{id}/payout-methods"),
    "Merchants_remove": ("DELETE", "/v1/merchants/{id}"),
    "Merchants_setDefaultPayoutMethod": ("POST", "/v1/merchants/{id}/payout-methods/{methodId}/default"),
    "Merchants_startVerify": ("POST", "/v1/merchants/{id}/verify/start"),
    "Merchants_startVerifyMethod": ("POST", "/v1/merchants/{id}/payout-methods/{methodId}/verify/start"),
    "Merchants_transfer": ("POST", "/v1/merchants/{id}/transfers"),
    "Merchants_update": ("PATCH", "/v1/merchants/{id}"),
    "Notifications_sendTest": ("POST", "/v1/notifications/test"),
    "PaymentLinks_get": ("GET", "/v1/payment-links/{id}"),
    "PaymentLinks_remove": ("DELETE", "/v1/payment-links/{id}"),
    "PaymentLinks_update": ("PATCH", "/v1/payment-links/{id}"),
    "Payments_executeC2p": ("POST", "/v1/payments/c2p"),
    "Payments_executeVpos": ("POST", "/v1/payments/vpos"),
    "Payments_getBanks": ("GET", "/v1/banks"),
    "Payments_getPayment": ("GET", "/v1/payments/{id}"),
    "Payments_getPaymentByRef": ("GET", "/v1/payments/by-ref/{externalRef}"),
    "Payments_getQuote": ("GET", "/v1/quote"),
    "Payments_requestC2p": ("POST", "/v1/payments/c2p/request"),
    "Payments_reversePayment": ("POST", "/v1/payments/{id}/reverse"),
    "Payments_verifyPagoMovil": ("POST", "/v1/payments/pago-movil/verify"),
    "Payouts_create": ("POST", "/v1/payouts"),
    "Payouts_createBatch": ("POST", "/v1/payouts/batch"),
    "Payouts_createInstant": ("POST", "/v1/payouts/instant"),
    "Payouts_getById": ("GET", "/v1/payouts/{id}"),
    "Payouts_getByRef": ("GET", "/v1/payouts/by-ref/{externalRef}"),
    "Payouts_list": ("GET", "/v1/payouts"),
    "Products_create": ("POST", "/v1/products"),
    "Products_createLink": ("POST", "/v1/products/{id}/links"),
    "Products_get": ("GET", "/v1/products/{id}"),
    "Products_list": ("GET", "/v1/products"),
    "Products_listLinks": ("GET", "/v1/products/{id}/links"),
    "Products_remove": ("DELETE", "/v1/products/{id}"),
    "Products_update": ("PATCH", "/v1/products/{id}"),
    "R4Operations_consultarOperacion": ("GET", "/v1/payments/operations/{id}"),
    "R4Operations_creditoCuentas": ("POST", "/v1/payments/credit/account"),
    "R4Operations_creditoInmediato": ("POST", "/v1/payments/credit"),
    "R4Operations_debitoInmediato": ("POST", "/v1/payments/debit"),
    "R4Operations_dispersarCredito": ("POST", "/v1/payments/credit/disburse"),
    "R4Operations_dispersarPagos": ("POST", "/v1/payments/payouts"),
    "R4Operations_ejecutarVuelto": ("POST", "/v1/payments/change"),
    "R4Operations_generarOtp": ("POST", "/v1/payments/debit/otp"),
    "R4Operations_pollOperation": ("POST", "/v1/payments/operations/poll"),
    "TenantPayoutAccount_confirmVerify": ("POST", "/v1/tenant/payout-account/verify"),
    "TenantPayoutAccount_get": ("GET", "/v1/tenant/payout-account"),
    "TenantPayoutAccount_startVerify": ("POST", "/v1/tenant/payout-account/verify/start"),
    "TenantPayoutAccount_upsert": ("PUT", "/v1/tenant/payout-account"),
    "TenantPayoutAccount_upsertPost": ("POST", "/v1/tenant/payout-account"),
    "Webhooks_createWebhook": ("POST", "/v1/webhooks"),
    "Webhooks_deleteWebhook": ("DELETE", "/v1/webhooks/{id}"),
    "Webhooks_listWebhooks": ("GET", "/v1/webhooks"),
    "Webhooks_updateWebhook": ("PATCH", "/v1/webhooks/{id}"),
}

#: Success response schema per operation (None: inline or empty body).
RESPONSE_MODELS: dict[str, Optional[str]] = {
    "Balance_getBalance": "PlatformBalanceDto",
    "CheckoutSessions_create": "CheckoutSessionResponseDto",
    "CheckoutSessions_retrieve": "CheckoutSessionResponseDto",
    "Merchants_addPayoutMethod": "PayoutMethodResponseDto",
    "Merchants_confirmVerify": "VerifyConfirmResponseDto",
    "Merchants_confirmVerifyMethod": "VerifyConfirmResponseDto",
    "Merchants_create": "MerchantResponseDto",
    "Merchants_deletePayoutMethod": None,
    "Merchants_getBalance": "MerchantBalanceDto",
    "Merchants_getById": "MerchantResponseDto",
    "Merchants_listAuditEvents": "MerchantAuditEventListDto",
    "Merchants_listOrGetByRef": None,
    "Merchants_listPayoutMethods": "PayoutMethodListResponseDto",
    "Merchants_remove": "DeleteMerchantResponseDto",
    "Merchants_setDefaultPayoutMethod": "PayoutMethodResponseDto",
    "Merchants_startVerify": "VerifyStartResponseDto",
    "Merchants_startVerifyMethod": "VerifyStartResponseDto",
    "Merchants_transfer": "MerchantBalanceDto",
    "Merchants_update": "MerchantResponseDto",
    "Notifications_sendTest": "NotificationTestResponseDto",
    "PaymentLinks_get": "PaymentLinkResponseDto",
    "PaymentLinks_remove": None,
    "PaymentLinks_update": "PaymentLinkResponseDto",
    "Payments_executeC2p": "PaymentReceiptDto",
    "Payments_executeVpos": "PaymentReceiptDto",
    "Payments_getBanks": None,
    "Payments_getPayment": "PaymentReceiptDto",
    "Payments_getPaymentByRef": "PaymentReceiptDto",
    "Payments_getQuote": "QuoteResponseDto",
    "Payments_requestC2p": "C2pIntentResponseDto",
    "Payments_reversePayment": "PaymentReceiptDto",
    "Payments_verifyPagoMovil": "PaymentReceiptDto",
    "Payouts_create": "PayoutResponseDto",
    "Payouts_createBatch": "PayoutBatchResponseDto",
    "Payouts_createInstant": "PayoutResponseDto",
    "Payouts_getById": "PayoutResponseDto",
    "Payouts_getByRef": "PayoutResponseDto",
    "Payouts_list": "PayoutListResponseDto",
    "Products_create": "ProductResponseDto",
    "Products_createLink": "PaymentLinkResponseDto",
    "Products_get": "ProductResponseDto",
    "Products_list": "ProductListResponseDto",
    "Products_listLinks": "PaymentLinkListResponseDto",
    "Products_remove": None,
    "Products_update": "ProductResponseDto",
    "R4Operations_consultarOperacion": "R4OperationResponseDto",
    "R4Operations_creditoCuentas": "R4OperationResponseDto",
    "R4Operations_creditoInmediato": "R4OperationResponseDto",
    "R4Operations_debitoInmediato": "ImmediateDebitResponseDto",
    "R4Operations_dispersarCredito": "CreditDisbursementResponseDto",
    "R4Operations_dispersarPagos": "AccountPayoutDispersionResponseDto",
    "R4Operations_ejecutarVuelto": "ChangePaymentResponseDto",
    "R4Operations_generarOtp": "DebitOtpResponseDto",
    "R4Operations_pollOperation": "ManualOperationPollResponseDto",
    "TenantPayoutAccount_confirmVerify": "TenantPayoutAccountVerifyConfirmResponseDto",
    "TenantPayoutAccount_get": "TenantPayoutAccountResponseDto",
    "TenantPayoutAccount_startVerify": "TenantPayoutAccountVerifyStartResponseDto",
    "TenantPayoutAccount_upsert": "TenantPayoutAccountResponseDto",
    "TenantPayoutAccount_upsertPost": "TenantPayoutAccountResponseDto",
    "Webhooks_createWebhook": "WebhookEndpointDto",
    "Webhooks_deleteWebhook": "DeleteWebhookResponseDto",
    "Webhooks_listWebhooks": None,
    "Webhooks_updateWebhook": "WebhookEndpointDto",
}
